/*
. vazio | J jogador decorativo | G portal | C moeda | H perigo
B terreno fundível | P plataforma conectável | S plataforma separada
*/

export const menuMap = `
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
...................C.C....G...
...C..............PPPPP.......
..PPP..J..HH......PPPPP...G...
BBBBBBBBBBBBBB...BBBBBBBBBBBBB
BBBBBBBBBBBBBB...BBBBBBBBBBBBB
BBBBBBBBBBBBBB...BBBBBBBBBBBBB
`;
