/*
. vazio | J jogador decorativo | G portal | C moeda | H perigo
B terreno fundível | P plataforma conectável | S plataforma separada
*/

export const menuMap = `
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.......C............C.C........
..J...PPP..H........PPP...G...
BBBBBBBBBBBBBB....BBBBBBBBBBBB
BBBBBBBBBBBBBB....BBBBBBBBBBBB
BBBBBBBBBBBBBB....BBBBBBBBBBBB
`;
